/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "on-secondary-container": "#007432",
        "surface-container-highest": "#dae2fd",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "secondary-fixed": "#6bff8f",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-variant": "#dae2fd",
        "on-secondary-fixed": "#002109",
        "secondary-fixed-dim": "#4ae176",
        "inverse-primary": "#8bd79b",
        "on-primary-fixed-variant": "#005226",
        "tertiary-container": "#7d4e00",
        "on-tertiary-container": "#ffc47d",
        "on-error": "#ffffff",
        "primary": "#004c22",
        "secondary-container": "#6bff8f",
        "primary-container": "#166534",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#404940",
        "tertiary": "#5d3900",
        "on-secondary-fixed-variant": "#005321",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-low": "#f2f3ff",
        "on-primary-container": "#93e0a2",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed": "#00210b",
        "surface-dim": "#d2d9f4",
        "tertiary-fixed": "#ffddb8",
        "surface-container": "#eaedff",
        "on-surface": "#131b2e",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#8bd79b",
        "primary-fixed": "#a6f4b5",
        "surface-bright": "#faf8ff",
        "secondary": "#006e2f",
        "surface-tint": "#1f6c3a",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-background": "#131b2e",
        "background": "#faf8ff",
        "outline-variant": "#bfc9bd",
        "outline": "#707a6f",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "margin-tablet": "2rem",
        "space-2xs": "0.25rem",
        "gutter-desktop": "2rem",
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "space-md": "1rem",
        "margin-desktop": "3rem",
        "gutter-tablet": "1.5rem",
        "space-2xl": "3rem",
        "margin-mobile": "1rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "space-3xl": "4rem",
        "gutter-mobile": "1rem"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "metric-val": ["Inter", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "display-mobile": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["0.6875rem", { lineHeight: "1.15", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-xl-mobile": ["1.75rem", { lineHeight: "1.25", letterSpacing: "-0.015em", fontWeight: "700" }],
        "metric-val": ["1.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["0.75rem", { lineHeight: "1.2", letterSpacing: "0.025em", fontWeight: "600" }],
        "headline-md": ["1.25rem", { lineHeight: "1.35", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["2.25rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.4", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-lg": ["1.5rem", { lineHeight: "1.3", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-md": ["1rem", { lineHeight: "1.55", fontWeight: "400" }],
        "display": ["3rem", { lineHeight: "1.15", letterSpacing: "-0.025em", fontWeight: "800" }],
        "display-mobile": ["2.25rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    },
  },
  plugins: [],
};
